### ISSUE TITLE
Regarding the accuracy of AAA on AutoAttack

### ISSUE THREAD

**Issue by StarryLogy** [Sizhe-Chen/AAA#2]
Thank you for your work, it is excellent! I tested the accuracy of the square attack on AutoAttack by calling your AAALinear code, but the robust accuracy of the test results differs significantly from the accuracy in your paper. Could you please explain the reason for this?

**Comment by Sizhe-Chen** [comment]
Thanks for your interest! AAA cannot defend against white-box AutoAttack. To test square attacks, this repo uses the official implementation from the square attack paper https://github.com/max-andr/square-attack. You are welcome to compare the implementation difference of square attacks in the official repo and in AutoAttack.
